### ISSUE TITLE
latest releases miss the APK

### ISSUE THREAD

**Issue by IzzySoft** [samu-developments/SpotMute#11]
Can you please continue providing the APK file at release tags for those without Playstore access? The last 3 releases are missing it. Thanks in advance!

**Comment by samu-developments** [comment]
Sorry about that, added now for 2.0.2!

**Comment by IzzySoft** [comment]
Cool, thanks a lot! My updater picked it up fine, so it should [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.developments.samu.muteforspotify) with the next sync – and existing users will receive the update notification from their F-Droid app if they use my repo (many are :smile:).
